<?php
/**
 * This file has been @generated by a dev-corner.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * You can modify this file via passing your DB object
 */

namespace CodeCorner\Validation\config;

use Exception;

/**
 * configuration class for validation
 */
class config
{

    public static $defaultConfiguration = [
        'DEFAULT_PHONE_CODE' => 'IN'

    ];
    
    /**
     * SQLQueries
     *
     * @param  mixed $query
     * @param  mixed $type
     * @return bool
     */
    public static function SQLQueries($query, $type)
    {
        $valid = true;
        switch ($type) {
            case 'unique':
                $valid = !DB::get()->get->query($query)->fetch_assoc()['count'];
                break;

            case 'not_in':
                $valid = !DB::get()->get->query($query)->fetch_assoc()['count'];
                break;

            case 'in':
                $valid = DB::get()->get->query($query)->fetch_assoc()['count'];
                break;

            case 'assign':
                $valid = DB::get()->get->query($query)->fetch_assoc()['count'];
                break;

            default:
                
                break;
        }

        return $valid;
    }

    /**
     * get
     *
     * @param  mixed $key
     * @return mixed
     */
    public static function get($key)
    {
        if (isset(self::$defaultConfiguration[$key])) {
            return self::$defaultConfiguration[$key];
        } else {
            throw new Exception('Call to undefined configuation ' . $key);
        }
    }
}
